name: SnakeXtreme
options:
  bundleIdPrefix: com.pixelatedstudios
targets:
  SnakeXtreme:
    type: application
    platform: iOS
    sources: [SnakeXtreme]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.pixelatedstudios.sX
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: ""  # empty for now, will skip signing
