name: Build SnakeXtreme iOS with XcodeGen

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # install ruby & cocoapods
          brew install ruby
          gem install cocoapods
          # install xcodegen
          brew install xcodegen

      - name: Generate Xcode project
        run: |
          xcodegen generate --spec "${{ github.workspace }}/project.yml" --quiet

      - name: Install pods
        run: |
          pod install --repo-update

      - name: Build and Archive
        run: |
          xcodebuild archive \
            -workspace "SnakeXtreme.xcworkspace" \
            -scheme "SnakeXtreme" \
            -configuration Release \
            -archivePath ${{ github.workspace }}/build/SnakeXtreme.xcarchive \
            INFOPLIST_FILE="${{ github.workspace }}/SnakeXtreme/Info.plist"

      - name: Export .ipa
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/build/SnakeXtreme.xcarchive \
            -exportPath ${{ github.workspace }}/build \
            -exportOptionsPlist ${{ github.workspace }}/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: SnakeXtreme.ipa
          path: ${{ github.workspace }}/build/SnakeXtreme.ipa
